//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicControllerMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        public int CustomFieldID { get; set; }
        public string CustomFieldName { get; set; }
        public Nullable<int> CustomFieldTypeID { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsAlive { get; set; }
        public string CustomFieldDefaultValue { get; set; }
        public Nullable<int> TableIndex { get; set; }
    }
}
