//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicControllerMain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PicStoreEntities1 : DbContext
    {
        public PicStoreEntities1()
            : base("name=PicStoreEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomField> CustomField { get; set; }
        public virtual DbSet<CustomFieldData> CustomFieldData { get; set; }
        public virtual DbSet<CustomFieldDataList> CustomFieldDataList { get; set; }
        public virtual DbSet<CustomFieldType> CustomFieldType { get; set; }
        public virtual DbSet<Order> Order { get; set; }
    }
}
