//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicControllerMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public string ShopPhone { get; set; }
        public string ShopEmail { get; set; }
        public string ShopWeiXin { get; set; }
        public string ShopQQ { get; set; }
        public string ShopFax { get; set; }
    }
}
